version: '3.7'

volumes:
  node_modules:

services:
  tourguide:
    container_name: tourguide
    build:
      context: ./
      dockerfile: Dockerfile
    image: jhernandezv/rn-tourguide:dev
    command: yarn start
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
      - '19003:19003'
      - '19006:19006'
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.8
